# Generated by Django for coursessvc

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('credits', models.PositiveSmallIntegerField()),
                ('aim', models.TextField()),
                ('assessment_type', models.CharField(blank=True, choices=[('EXAM', 'Exam'), ('PROJECT', 'Project'), ('ASSIGNMENT', 'Assignment'), ('MIX', 'Mix')], max_length=16, null=True)),
                ('study_area', models.CharField(blank=True, choices=[('BEL', 'Business, Economics & Law'), ('EAIT', 'Engineering, Architecture & Information Technology'), ('HABS', 'Health & Behavioural Sciences'), ('HMB', 'Health, Medicine and Behavioural Sciences'), ('HASS', 'Humanities, Arts & Social Sciences'), ('SCI', 'Science')], max_length=128, null=True)),
                ('offered_sem_1', models.BooleanField(default=False)),
                ('offered_sem_2', models.BooleanField(default=False)),
                ('offered_summer', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_links', to='coursessvc.course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_prerequisite_for', to='coursessvc.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocking_courses', through='coursessvc.CoursePrerequisite', to='coursessvc.course'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('grading_type', models.CharField(choices=[('percentage', 'Percentage'), ('pass_fail', 'Pass/Fail')], default='percentage', max_length=20)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField()),
                ('hurdle', models.BooleanField(default=False)),
                ('hurdle_description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='coursessvc.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='coursessvc.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseprerequisite',
            constraint=models.UniqueConstraint(fields=('course', 'prereq'), name='coursessvc_courseprerequisite_course_prereq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='courseprerequisite',
            constraint=models.CheckConstraint(check=models.Q(('course', models.F('prereq')), _negated=True), name='course_prereq_no_self_ref'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='coursessvc_coursereview_user_course_uniq'),
        ),
    ]
