# Generated by Django 5.2.6 on 2025-10-14 09:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('credits', models.PositiveSmallIntegerField()),
                ('aim', models.TextField()),
                ('assessment_type', models.CharField(blank=True, choices=[('Exam', 'Exam'), ('Project', 'Project'), ('Assignment', 'Assignment'), ('Mix', 'Mix')], max_length=16, null=True)),
                ('study_area', models.CharField(blank=True, choices=[('Business, Economics & Law', 'Business, Economics & Law'), ('Engineering, Architecture & Information Technology', 'Engineering, Architecture & Information Technology'), ('Health & Behavioural Sciences', 'Health & Behavioural Sciences'), ('Health, Medicine and Behavioural Sciences', 'Health, Medicine and Behavioural Sciences'), ('Humanities, Arts & Social Sciences', 'Humanities, Arts & Social Sciences'), ('Science', 'Science')], max_length=128, null=True)),
                ('offered_sem_1', models.BooleanField(default=False)),
                ('offered_sem_2', models.BooleanField(default=False)),
                ('offered_summer', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField()),
                ('hurdle', models.BooleanField(default=False)),
                ('hurdle_description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_links', to='api.course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_prerequisite_for', to='api.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocking_courses', through='api.CoursePrerequisite', to='api.course'),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_by', to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('course', models.F('prereq')), _negated=True), name='course_prereq_no_self_ref'),
        ),
        migrations.AlterUniqueTogether(
            name='courseprerequisite',
            unique_together={('course', 'prereq')},
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='plannedcourse',
            unique_together={('user', 'course', 'semester')},
        ),
    ]
