# Generated by Django 5.2.6 on 2025-10-14 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='grading_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('pass_fail', 'Pass/Fail')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='assessment_type',
            field=models.CharField(blank=True, choices=[('EXAM', 'Exam'), ('PROJECT', 'Project'), ('ASSIGNMENT', 'Assignment'), ('MIX', 'Mix')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_area',
            field=models.CharField(blank=True, choices=[('BEL', 'Business, Economics & Law'), ('EAIT', 'Engineering, Architecture & Information Technology'), ('HABS', 'Health & Behavioural Sciences'), ('HMB', 'Health, Medicine and Behavioural Sciences'), ('HASS', 'Humanities, Arts & Social Sciences'), ('SCI', 'Science')], max_length=128, null=True),
        ),
    ]
