# Generated by Django 5.2.7 on 2025-10-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assessment_grading_type_alter_assessment_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_level', models.CharField(choices=[('UNDERGRAD', 'Under Graduate'), ('POSTGRAD', 'Post Graduate')], max_length=16)),
                ('program', models.CharField(max_length=255)),
                ('year_intake', models.CharField(choices=[('SEM1', 'Semester 1'), ('SEM2', 'Semester 2')], max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
