# Generated by Django 5.2.7 on 2025-10-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('level', models.CharField(choices=[('UNDERGRAD', 'Undergraduate'), ('POSTGRAD', 'Postgraduate')], max_length=16)),
            ],
        ),
    ]
