# Generated by Django 5.2.7 on 2025-10-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='mode',
            field=models.CharField(max_length=255),
        ),
    ]
