# Generated by Django for plannersvc

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_code', models.CharField(max_length=32)),
                ('course_name', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='plannedcourse',
            constraint=models.UniqueConstraint(fields=('user', 'course_id', 'semester'), name='plannersvc_plannedcourse_user_course_semester_uniq'),
        ),
    ]
