apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ccproject
  labels:
    app: auth-svc
spec:
  selector:
    app: auth-svc
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc
  namespace: ccproject
  labels:
    app: auth-svc
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: auth-svc
        version: v1
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: auth-svc
        image: gcr.io/model-obelisk-469607-r0/ccproject-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: ccproject-config
              key: DEBUG
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ccproject-secrets
              key: SECRET_KEY
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ccproject-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ccproject-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ccproject-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: ccproject-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccproject-secrets
              key: DB_PASSWORD
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: ccproject-config
              key: ALLOWED_HOSTS
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: ccproject-config
              key: CORS_ALLOWED_ORIGINS
        - name: DJANGO_SETTINGS_MODULE
          value: "backend.settings_auth"
        command: ["/bin/sh", "-c"]
        args:
          - |
            python manage.py migrate --noinput &&
            gunicorn backend.wsgi:application --bind 0.0.0.0:8001 --workers 3 --timeout 120
        livenessProbe:
          httpGet:
            path: /api/auth/health/
            port: 8001
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/auth/health/
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
